## Necessary homework

In [52]:
import torch

In [53]:
# Создайте случайный FloatTensor размера 3x4x5
torch.manual_seed(95)
x = torch.randn(3, 4, 5)
x

tensor([[[-1.2251, -0.1323, -1.5998,  1.8705, -1.8059],
         [-1.0359, -0.2606,  0.5811,  0.4520,  0.5354],
         [-0.9098,  0.3962,  1.2298,  1.8889,  0.1557],
         [ 0.8910, -1.2491, -1.1928, -0.9749, -1.0453]],

        [[ 0.4850, -1.2354, -0.0368, -1.6307, -0.2499],
         [-0.8968,  0.7578,  0.3496,  0.2665, -0.0693],
         [ 0.9668, -1.3419, -0.5262,  1.9816,  0.2943],
         [-0.5964, -0.4167,  1.4757,  0.9589,  0.9032]],

        [[ 1.1658, -0.0424,  0.6769, -0.2416,  0.8314],
         [ 0.3790, -1.1093,  2.3114, -1.0568, -1.2111],
         [-1.1390, -0.6333,  0.8112,  0.5545,  1.9656],
         [-0.8900, -2.1538, -1.9405, -1.2175, -0.8657]]])

In [54]:
# Выведите его форму (shape)
x.size()

torch.Size([3, 4, 5])

In [55]:
# Приведите его к форме 6 X 10
x = x.view(6, 10)
x

tensor([[-1.2251, -0.1323, -1.5998,  1.8705, -1.8059, -1.0359, -0.2606,  0.5811,
          0.4520,  0.5354],
        [-0.9098,  0.3962,  1.2298,  1.8889,  0.1557,  0.8910, -1.2491, -1.1928,
         -0.9749, -1.0453],
        [ 0.4850, -1.2354, -0.0368, -1.6307, -0.2499, -0.8968,  0.7578,  0.3496,
          0.2665, -0.0693],
        [ 0.9668, -1.3419, -0.5262,  1.9816,  0.2943, -0.5964, -0.4167,  1.4757,
          0.9589,  0.9032],
        [ 1.1658, -0.0424,  0.6769, -0.2416,  0.8314,  0.3790, -1.1093,  2.3114,
         -1.0568, -1.2111],
        [-1.1390, -0.6333,  0.8112,  0.5545,  1.9656, -0.8900, -2.1538, -1.9405,
         -1.2175, -0.8657]])

In [57]:
# Умножьте его на случайный вектор размерности (1, 10) поэлементно
y = torch.randn(10)
z = x * y
print(f'X at the beginning:\n{x}\n\nGenerated vector:\n{y}\n\nMultiply each row of X by the vector:\n{z}')

X at the beginning:
tensor([[-1.2251, -0.1323, -1.5998,  1.8705, -1.8059, -1.0359, -0.2606,  0.5811,
          0.4520,  0.5354],
        [-0.9098,  0.3962,  1.2298,  1.8889,  0.1557,  0.8910, -1.2491, -1.1928,
         -0.9749, -1.0453],
        [ 0.4850, -1.2354, -0.0368, -1.6307, -0.2499, -0.8968,  0.7578,  0.3496,
          0.2665, -0.0693],
        [ 0.9668, -1.3419, -0.5262,  1.9816,  0.2943, -0.5964, -0.4167,  1.4757,
          0.9589,  0.9032],
        [ 1.1658, -0.0424,  0.6769, -0.2416,  0.8314,  0.3790, -1.1093,  2.3114,
         -1.0568, -1.2111],
        [-1.1390, -0.6333,  0.8112,  0.5545,  1.9656, -0.8900, -2.1538, -1.9405,
         -1.2175, -0.8657]])

Generated vector:
tensor([-1.0460,  1.0076,  0.4988, -2.7705,  1.5705, -1.0315,  1.4457,  0.6159,
        -0.5116,  0.5125])

Multiply each row of X by the vector:
tensor([[ 1.2814, -0.1333, -0.7979, -5.1822, -2.8360,  1.0685, -0.3767,  0.3579,
         -0.2312,  0.2744],
        [ 0.9516,  0.3993,  0.6134, -5.2333,  0.244

In [58]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
x_matmulted = torch.matmul(x, x.T)
print(f'X:\n{x}\n\nX multiplied by itself (but transposed):\n{x_matmulted}')

X:
tensor([[-1.2251, -0.1323, -1.5998,  1.8705, -1.8059, -1.0359, -0.2606,  0.5811,
          0.4520,  0.5354],
        [-0.9098,  0.3962,  1.2298,  1.8889,  0.1557,  0.8910, -1.2491, -1.1928,
         -0.9749, -1.0453],
        [ 0.4850, -1.2354, -0.0368, -1.6307, -0.2499, -0.8968,  0.7578,  0.3496,
          0.2665, -0.0693],
        [ 0.9668, -1.3419, -0.5262,  1.9816,  0.2943, -0.5964, -0.4167,  1.4757,
          0.9589,  0.9032],
        [ 1.1658, -0.0424,  0.6769, -0.2416,  0.8314,  0.3790, -1.1093,  2.3114,
         -1.0568, -1.2111],
        [-1.1390, -0.6333,  0.8112,  0.5545,  1.9656, -0.8900, -2.1538, -1.9405,
         -1.2175, -0.8657]])

X multiplied by itself (but transposed):
tensor([[12.8071,  0.0557, -1.9528,  5.5107, -4.3454, -2.9893],
        [ 0.0557, 11.9097, -6.4453, -1.9197,  0.6906,  9.4403],
        [-1.9528, -6.4453,  6.0608, -0.2308,  0.2091, -2.9722],
        [ 5.5107, -1.9197, -0.2308, 11.4677,  2.1336, -2.3855],
        [-4.3454,  0.6906,  0.2091,  2.1336,

In [47]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
x, z, t = (1, 0.5, 2)
y = x**3 + z - 75*t
y_der = (3*x)**2 + 1 - 75
y_der

-65

In [49]:
# Создайте единичный тензор размера 5x6
x_ones = torch.ones(5, 6)
x_ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [51]:
# Переведите его в формат numpy
x_ones.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [60]:
print(f"Поддерживается ли CUDA : {torch.cuda.is_available()}")
print(f'Количество гпу девайсов: {torch.cuda.device_count()}')
print(f":(")

Поддерживается ли CUDA : False
Количество гпу девайсов: 0
:(


## Optional tasks 

### Creating a fully connected layer with n_neurons.   

Let's create an input vector of a random size.  
Set any number of neurons in the hidden layer.  
And set the output to 1 neuron. So it's meant to be a single scalar (let's pretend it's a regression task). 

In [137]:
n_features = 5  # size of the input vector
n_neurons_1 = 10  # number of neurons in a hidden layer
n_neurons_2 = 1  # number of neurons in the output layer

# input vector
x = torch.rand(n_features)

# layer 1 weights + bias
w1 = torch.rand(n_neurons_1, n_features, requires_grad=True)
b1 = torch.rand(n_neurons_1, requires_grad=True)

# layer 1 forward pass
activation_function = torch.sigmoid
layer_1 = activation_function((x * w1).sum(dim=1) + b1)

# output layer weights + bias
w2 = torch.rand(n_neurons_2, n_neurons_1, requires_grad=True)
b2 = torch.rand(n_neurons_2, requires_grad=True)

# output layer results
activation_function = torch.relu

output = activation_function((layer_1 * w2).sum(dim=1) + b2)

# mock the loss
L = (10 - output)

# do backpropagation step
L.backward()

In [140]:
print(f'Gradients for the Weight Matrix 1:\n{w1.grad}\n\nGradients for the Bias Vector 1:\n{b1}'
      f'\n\nGradients for the Weight Matrix 2:\n{w2.grad}\n\nGradients for the Bias Vector 2:\n{b2}')

Gradients for the Weight Matrix 1:
tensor([[-0.0654, -0.0765, -0.0420, -0.0527, -0.0145],
        [-0.0423, -0.0495, -0.0272, -0.0341, -0.0094],
        [-0.0136, -0.0159, -0.0087, -0.0109, -0.0030],
        [-0.0600, -0.0702, -0.0386, -0.0483, -0.0133],
        [-0.1116, -0.1305, -0.0717, -0.0899, -0.0248],
        [-0.0113, -0.0132, -0.0072, -0.0091, -0.0025],
        [-0.0261, -0.0306, -0.0168, -0.0210, -0.0058],
        [-0.0011, -0.0012, -0.0007, -0.0009, -0.0002],
        [-0.0455, -0.0532, -0.0293, -0.0367, -0.0101],
        [-0.0501, -0.0586, -0.0322, -0.0404, -0.0111]])

Gradients for the Bias Vector 1:
tensor([0.1969, 0.7229, 0.8916, 0.3135, 0.2281, 0.3442, 0.6012, 0.8099, 0.7866,
        0.8336], requires_grad=True)

Gradients for the Weight Matrix 2:
tensor([[-0.8589, -0.9268, -0.9563, -0.7424, -0.7839, -0.7830, -0.8072, -0.8309,
         -0.8473, -0.9058]])

Gradients for the Bias Vector 2:
tensor([0.6832], requires_grad=True)


#### Results:
This way we can calculate gradients manually. With a bit of time it's easy to implement learning rate here, make a for loop, and train the very basic model for a few epochs, measuring the loss on each step :)

### Torch Layers intro

In [171]:
# Super basec imitation of a perceptron with a torch Linear layer
# A fully connected layer, trained for n_epochs, measuring the loss

layer = torch.nn.Linear(
    in_features=5,
    out_features=10,
    bias=True
)

optimizer = torch.optim.SGD(layer_1.parameters(), lr=0.01)
loss_func = torch.nn.MSELoss()

X = torch.rand(5)
y = torch.rand(10)

n_epochs = 10

for i in range(n_epochs):
    predictions = layer_1(X)
    loss = loss_func(predictions, y)
    print(f'loss: {loss:.4f}')
    loss.backward()
    optimizer.step()

loss: 0.1916
loss: 0.2081
loss: 0.2255
loss: 0.2434
loss: 0.2614
loss: 0.2792
loss: 0.2964
loss: 0.3127
loss: 0.3276
loss: 0.3410
